<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Rekognition" Version="4.0.3.27" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.23" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App_Data\facesets\" />
    <Folder Include="NewFolder\" />
  </ItemGroup>

</Project>
